---
title: "CC Prescreen & Pretest Results"

output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 1
    toc_float:
      collapsed: true
    code_folding: hide
    

---
# Community College Prescreen & Pretest Results

Community college students who participated in our studies were recruited from a larger pool of students who took our Aptitude and Math Skills Assessment (AMSA) as part of the Research Experience Program (REP) at their school. This AMSA consisted of a battery of tasks that can be divided into the following four categories: aptitude tasks, basic math tasks, supported math tasks, and trigonometry-specific math tasks. Students also answered demographic questions as well as questions about their math attitude and spatial abilities. The purpose of the AMSA was to help our team identify ability and/or preparation related factors that may predict how well students would perform on our materials and give us the opportunity to provide additional support to students who may not have the requisite skills needed to succeed on our existing curriculum. Between fall 2016 and fall 2018, we collected complete pretest and prescreen results for 1,967 students. 

These students' scores on each section of the AMSA and prescreen can be found in the downloadable .csv file below. The raw data can be found on GitHub in the "allREPResults.rds" and "PrescreenResultsFall16-Fall18.csv" files and the code used to process the raw data file into the .csv file below can be found in the "REPPrescreenPretestDataProcess.R" file. 

```{r}
library(magrittr)
readLines("allREPPrescreenPretestResults.csv") %>% 
  paste0(collapse="\n") %>% 
  openssl::base64_encode() -> encoded
```

<a download="allREPPrescreenPretestResults.csv" href="`r sprintf('data:text/csv;base64,%s', encoded)`">Download All CC Prescreen/Pretest Results (n=1967)</a>

