---
title: "Materials"

output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 1
    toc_float:
      collapsed: true
    code_folding: hide
    

---

On this page you can download the raw results data as it was pulled directly from our database. You can also download the contents of our entire curriculum including the pretest, lesson materials, and posttest. 

# Raw Data

Download Post Jan 2017 High School Raw Data: https://osf.io/w4jrt/ 

Download All Community College and Pre Jan 2017 HS Raw Data: https://osf.io/fx9v4/

Download User ID Data: https://osf.io/6m9qu/

# Curriculum

**Download the curriculum questions:** https://osf.io/2cnqw/. Note: the curriculum consisted of six chapters, divided into several pages. These six chapters included: 1) XY Positions; 2) Circle Positions; 3) Circle Rotations; 4) Linking the Circle with the XY Plane; 5) Rotations, Reflections, and Positions; and 6) Comparing Values. 

**Download the pretest questions:** https://github.com/trigacademy/grounded-unit-circle-trigonometry/tree/master/pretest_content. Note: the pretest consisted of the following 11 pages: 1) Mental Rotation; 2) Embedded Figure; 3) Letter Sets; 4) Advanced Vocabulary; 5) Addition and Subtraction; 6) Mark XY; 7) Mark XY Supported; 8) Mark Theta; 9) Mark Theta Supported; 10) Triangle Trigonometry; 11) Trigonometric Identities. 

We are unable to include access to the Letter Sets and Vocabulary tasks because they are copyrighted by ETS. For reference, we used the following questions from the 1976 ETS Letter Sets Test: **pre Jan 2017**: 1-8; 16-23; **post Jan 2017**: 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29. We used the following questions from the 1976 ETS Vocbulary Test: **pre Jan 2017**: Vocabulary Test I V-1: 1-36; **post Jan 2017**: Advanced Vocabulary Test I V-4: 1-36.

**Download the posttest questions:** https://github.com/trigacademy/grounded-unit-circle-trigonometry/tree/master/posttest_content Note: the posttest was made up of the following 5 pages: 1) Mark XY; 2) Mark Theta; 3) Triangle Trigonometry; 4) Trigonometric Identities with Circle Support; 5) Trigonometric Identities without Circle Support. 
